Update
Xiaokang2022/Visual-Programmer pull request #3
Opened 2024-01-20 13:44 UTC by CodeCrafter-TL

2024-01-20 15:36 UTC, Xiaokang2022 requested changes

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/img/sidebar/size.py
> +from PIL import Image
此文件中的代码使用完毕后应删除，不应该保留并放在PR中。

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +''' 设置默认搜索路径'''
docstring应该放在函数定义后的第一行

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +    print("设置路径："+open_path)
测试用的print函数在PR时应删去

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +def file_extension(file):
函数与函数、类之间应该空两行

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +def load_tree(root, patha, opened=[]):
尽量不要使用可变类型的数据作为默认参数，容易产生意想不到的bug

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +    root = tree.insert(root, END, text = " " + dir_name(patha), values = (patha,), open = is_open, image = folder_img)
参数名和参数值以及等号之间不要有空格

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +def get_opened(parent=None,last_res=[]):
函数定义时，参数之间应该空一格

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +    tree.bind("<<TreeviewSelect>>", lambda event:SelectCommand(tree.focus()))
lambda表达式中未使用的单个参数应用单下划线代替，表示这个参数只是占位，无实际用途

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +class ui_Menu(tk.Toplevel):
类名不符合规范，应该为驼峰法命名方式

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
> +        if self.pos=='cur':
==与两边应该各存有一个空格

2024-01-20 15:36 UTC, Xiaokang2022 commented on client/main.py
>  root.mainloop()
重复的问题我没有重复提及，自己对照着修改，建议格式化一下代码（推荐使用autopep8来格式化）

2024-01-25 05:38 UTC, closed without merging

2024-02-08 09:13 UTC, TotoWang-hhh commented on client/main.py
> +    print("设置路径："+open_path)
我都留着了，控制台只有排错的人去看，所以非常有必要让排错者时刻都知道程序里发生了和在发生什么，另外既然其他人不看，那么print再多也不会有很大的影响的

2024-02-08 09:33 UTC, Xiaokang2022 commented on client/main.py
> +    print("设置路径："+open_path)
> 我都留着了，控制台只有排错的人去看，所以非常有必要让排错者时刻都知道程序里发生了和在发生什么，另外既然其他人不看，那么print再多也不会有很大的影响的

按道理，PR里面应该没有错误，或者说，有错误的话就应该在PR之前解决，而不是将半成品的代码放上来。如果确有不太好解决的问题，应该用注释写明，而非用print。

可用的特殊注释：NOTE、FIXME、BUG、TODO、HACK 和 XXX 等，这些在IDE中一般会被高亮。下面是一个简单的示例：
```python
def func() -> None:
    pass  # BUG: 此处有……的问题，目前无法解决
```

2024-02-09 10:04 UTC, TotoWang-hhh commented on client/main.py
> +    print("设置路径："+open_path)
bug我肯定会写明在注释里（把代码交给别人时的基本道德），但是有没有一种可能我在讨论各种print的去留问题？😂

我觉得只要在print的内容里写明它在输出什么，那就还是留下比较好。